version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: apartment_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: qlchdv
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

volumes:
  mysql_data_dev:
